require_relative "./kefoto_scraper/version"
require "nokogiri"
require "httparty"
require "pry"
require_relative "./kefoto_scraper/CLI"
require_relative "./kefoto_scraper/products"
require_relative "./kefoto_scraper/scraper"
